steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA}'
      - '--build-arg'
      - 'FIREBASE_SERVICE_ACCOUNT=$$FIREBASE_SERVICE_ACCOUNT'
      - '.'
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT'] # This makes 'FIREBASE_SERVICE_ACCOUNT' available in this Cloud Build step

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA}'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--allow-unauthenticated' # Optional: Allow public access
      - '--port'
      - '3000' # Next.js default port

availableSecrets:
  secretManager:
  - versionName: projects/daily-quiz-464300/secrets/FIREBASE_SERVICE_ACCOUNT/versions/latest
    env: 'FIREBASE_SERVICE_ACCOUNT' # Map the secret to an environment variable named FIREBASE_SERVICE_ACCOUNT
options:
  logging: CLOUD_LOGGING_ONLY # <--- Add this section
  