steps:
  # Step 1: Run unit tests
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm test

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash' 
    args:
      - '-c'
      - |
        docker build -t ${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA} \
        --secret id=CSRF_SECRET,env=CSRF_SECRET \
        --secret id=FIREBASE_SERVICE_ACCOUNT,env=FIREBASE_SERVICE_ACCOUNT \
        --secret id=FIREBASE_WEB_CONFIG,env=FIREBASE_WEB_CONFIG \
        .
    secretEnv: 
      - 'CSRF_SECRET'
      - 'FIREBASE_SERVICE_ACCOUNT'
      - 'FIREBASE_WEB_CONFIG'

    env:
      - "DOCKER_BUILDKIT=1" # Enable Docker BuildKit

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA}'

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/daily-quiz:${COMMIT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--allow-unauthenticated' # Optional: Allow public access
      - '--port'
      - '3000' # Next.js default port

availableSecrets:
  secretManager:
  - versionName: projects/daily-quiz-464300/secrets/CSRF_SECRET/versions/latest
    env: 'CSRF_SECRET'
  - versionName: projects/daily-quiz-464300/secrets/FIREBASE_SERVICE_ACCOUNT/versions/latest
    env: 'FIREBASE_SERVICE_ACCOUNT'
  - versionName: projects/daily-quiz-464300/secrets/FIREBASE_WEB_CONFIG/versions/latest
    env: 'FIREBASE_WEB_CONFIG'
options:
  logging: CLOUD_LOGGING_ONLY
